### ISSUE TITLE
Barra de pesquisa não faz tratamento dos nomes

### ISSUE THREAD

**Issue by pedro-cella** [BeaReis/genshin-app#1]
## Barra de pesquisa não faz tratamento dos nomes

Na barra de pesquisa, ao se buscar um personagem utilizando de primeira letra maiúscula(capitalize) não é encontrado nenhum personagem, mesmo o nome estando certo. Logo é provável que ao digitar algum nome não esteja ocorrendo o devido tratamento, tranformar tudo em minúsculo, ou transformar tudo em maiúsculo, etc. Abaixo alguns prints para evidenciar esse problema:

### Utilizando letras minúsculas
![Captura de tela de 2022-09-06 11-16-32](https://user-images.githubusercontent.com/49076513/188659331-ac53fbb7-5727-4b4d-9b40-53764b8063a4.png)

### Utilizando primeira letra maiúscula
![Captura de tela de 2022-09-06 11-16-21](https://user-images.githubusercontent.com/49076513/188659342-0c18d00f-ba79-4c59-89d0-7c5d5b5223af.png)

**Comment by BeaReis** [comment]
Resolvido!
Passei o argumento da função como _lower case_ e agora ele aceita de qualquer forma.
![image](https://user-images.githubusercontent.com/63968003/189370151-11935c41-a6cd-4fb2-a2b4-64089f22c2ab.png)
